//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.ETL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dim_Empleado()
        {
            this.Fact_Orden = new HashSet<Fact_Orden>();
        }
    
        public int Empleado_Key { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public string Region { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fact_Orden> Fact_Orden { get; set; }
    }
}
