//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.ETL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Fecha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dim_Fecha()
        {
            this.Fact_Orden = new HashSet<Fact_Orden>();
        }
    
        public int Fecha_Key { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NombreDia { get; set; }
        public Nullable<int> SemanaDelMes { get; set; }
        public string NombreMes { get; set; }
        public Nullable<int> Trimestre { get; set; }
        public Nullable<int> Año { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fact_Orden> Fact_Orden { get; set; }
    }
}
